import {  Sora } from "next/font/google";
import "./globals.css";

const inder=Sora({
  subsets:["latin"],
  weight:["400"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inder.className}
      >
        {children}
      </body>
    </html>
  );
}
